### ISSUE TITLE
Intensity information missing in Page Info window and fitting window for .pt3 files

### ISSUE THREAD

**Issue by kyseerentant** [FCS-analysis/PyCorrFit#118]
When loading .pt3 files, the intensity information in both, the fitting window and page info window are missing. Also, Tools--> Trace view displays a blank page. 

Identical behaviour was observed with PyCorrFit 0.8.7 and 0.8.8 on Windows and Linux. Are there any limitations on which .pt3 file versions are supported?

**Comment by paulmueller** [comment]
The .pt3 file support is implemented in https://github.com/dwaithe/FCS_point_correlator by @dwaithe. 
I don't know if the intensity information is accessible right now.

Dominic (@dwaithe), could you please point me in the right direction?

**Comment by dwaithe** [comment]
Hi, 
Sorry for delay, I was at a conference. kyseerentant if you just want to view a time-trace you can use the software at:
https://github.com/dwaithe/FCS_point_correlator
It depends what you want to do with it. 

This is for you Paul:
It is possible to display the intensity information but it requires some binning. 

In the file 'correlation_objects.py' you find the lines:
#Time series of photon counts. For visualisation.
self.timeSeries1,self.timeSeriesScale1 = delayTime2bin(np.array(self.trueTimeArr)/1000000,np.array(self.subChanArr),self.ch_present[0],self.photonCountBin)
 #Converts to counts per 
self.kcount_CH1 = np.average(self.timeSeries1)

The function delayTime2bin is in the file 'correlation_methods.py'.
This takes the raw TCSPC data and bins it so that you can establish the intensity over-time. Furthermore if you average the output timeSeries you can get average counts, and this will be in the units of your bin size.

Hope that helps.
Best,
Dom.

**Comment by paulmueller** [comment]
Yes, thanks for the detailed answer. It should be not problem to implement this in PyCorrFit as well.

**Comment by paulmueller** [comment]
@kyseerentant 
The next version of PyCorrFit will incorporate the visualization of the trace. I am not certain if I implemented the normalization correctly. Could you provide me with a pt3 file whose average intensity you know? Then I can make sure the import works correctly.

**Comment by paulmueller** [comment]
Could anyone please verify that this is working correctly now?
https://ci.appveyor.com/api/buildjobs/sqrirfel2eub2wyt/artifacts/Output%2FPyCorrFit_1.0.0_win_32bit_setup.exe

**Comment by paulmueller** [comment]
@kyseerentant
Could you please verify that this is working correctly now?

https://ci.appveyor.com/api/buildjobs/q4huhmgwvtnvo9vb/artifacts/Output%2FPyCorrFit_1.0.0_win_64bit_setup.exe

**Comment by kyseerentant** [comment]
@paulmueller 
Thanks Paul for implementing the suggested feature and sorry for not getting back to you earlier. I just checked a couple of old .pt3 files and the traces+ average intensities computed by PyCorrFit match the ones in SymPhoTime.

**Comment by paulmueller** [comment]
Thanks!
