### ISSUE TITLE
Moving to python 3 and further development

### ISSUE THREAD

**Issue by toubol** [FCS-analysis/PyCorrFit#173]
Hi,
I wanted to know how you see the future development of PyCorrFit, because I moved it to Python 3 to keep it up to date and to use it with my own configuration. But now that it works well, how can I open it to the community?
As far as I tested it, it is successfully running on windows 10, python 3.6, and the files are fully compatible with the actual stable release.

**Comment by paulmueller** [comment]
Thanks for the question. I understood that you modified PyCorrFit to run under Python 3.6. Is that correct?
If you created a pull request, I would be very happy to merge it. Is it still compatible to Python 2.7? If not, then I would have to update the appveyor build pipeline as well.

I currently only have little time to further develop PyCorrFit. I am doing it in my free time.

**Comment by toubol** [comment]
It is exactly that, it is now running under Python 3.6, but I also added some shortcuts and small changes just to get it more comfortable to my use.
I don't expect it to run under python 2.7.
I'll create the pool request soon, I  just need to end commenting my changes.

**Comment by paulmueller** [comment]
To not break the current workflow of other users, I have reverted/changed some of your modifications:

- The behavior of text selection when the mouse enters a text field is an important feature that was requested earlier.
- Autoclosing tools is not a desired behavior, because many users need the tools more than once in a fitting session. I added a preferences menu option for autoclosing.
- For a detailed diff, please see https://github.com/FCS-analysis/PyCorrFit/commit/788e41631fa312078dae64a1ed045ddb67d718f5

**Comment by paulmueller** [comment]
TODO:
- [ ] test-run all tools (function, autoclose)
- [ ] test-run session saving and loading (also add tests)
- [ ] test-run export options (current page menu, with/without latex)
- [ ] fix appveyor builds (tests, pyinstaller, install on win10)
- [ ] update documentation (version numbers, preferences menu)
- [ ] rename ChangeLog.txt
- [ ] check MANIFEST.in
- [ ] remove all future imports and encoding declarations on top of all files
- [ ] remove outdated wiki pages (or all of it, since it is not used): https://github.com/FCS-analysis/PyCorrFit/wiki
- [ ] add notice on how to cite pycorrfit

**Comment by toubol** [comment]
Thank you for all your job. Even if I do not agree with all the changes, you better know the requested features.  
It keeps running fine and this is the most important for me.
I will continue to send you my changes, and try to take part to the to-do list.

**Comment by paulmueller** [comment]
One of the old memory leaks is gone in wxPython4 (close #157).
